LEAN-4230: support for images
Atypon-OpenSource/manuscripts-transform pull request #176
Opened 2024-12-19 14:46 UTC by mbetamony

2024-12-19 19:02 UTC, mnatsheh requested changes

2024-12-19 19:02 UTC, mnatsheh commented on src/schema/nodes/image.ts
> +export interface ImageNode extends ManuscriptNode {
This should be like a standard element node but without a caption; it should be called `imageElement` and its content should be `figure`.

2024-12-24 11:49 UTC, mbetamony commented on src/jats/importer/jats-transformations.ts
> +export const createImages = (doc: Document, createElement: CreateElement) => {
You're right, we can. Do we need to add support for content other than figure though? (placeholder | missing_figure)

2024-12-24 15:39 UTC, mnatsheh commented on src/jats/importer/jats-transformations.ts
> +export const createImages = (doc: Document, createElement: CreateElement) => {
I don't think so.

2024-12-30 16:22 UTC, mnatsheh approved these changes

2025-01-06 10:50 UTC, mbetamony commented
@mnatsheh, do you think we need to support a graphic inside a paragraph? :thinking:

2025-01-06 19:32 UTC, mnatsheh commented
We don't need to support either.

2025-01-08 10:57 UTC, merged