LEAN-2407
Atypon-OpenSource/manuscripts-transform pull request #20
Opened 2023-05-02 07:01 UTC by asouqi

2023-05-02 14:27 UTC, mnatsheh commented
There are some failing tests.

2023-05-09 18:26 UTC, asouqi commented
> There are some failing tests.

fix

2023-05-10 23:21 UTC, mnatsheh requested changes

2023-05-10 23:21 UTC, mnatsheh commented on package.json
> +    "@manuscripts/data": "1.0.1",
I believe that there is a 1.0.2 version of data, so let's use that. Also, you should have a caret there.

2023-05-10 23:53 UTC, mnatsheh commented on package.json
> +    "@manuscripts/data": "1.0.1",
Actually, we already have https://github.com/Atypon-OpenSource/manuscripts-transform/pull/18 which updates manuscripts-data to 1.0.2. We should just wait for that.

2023-05-11 14:43 UTC, closed without merging